### ISSUE TITLE
ErrorException: Method ReflectionParameter::getClass() is deprecated

### ISSUE THREAD

**Issue by ereznet** [ckfinder/ckfinder-laravel-package#64]
# php -v
PHP 8.0.3 (cli) (built: Mar 29 2021 22:51:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies

# php artisan --version
Laravel Framework 8.34.0

# ErrorException
[2021-04-09T14:33:31.837166+00:00] CKFinder.WARNING: ErrorException: Method ReflectionParameter::getClass() is deprecated in /home//domains/XXX/public_html/vendor/ckfinder/ckfinder-laravel-package/_connector/ArgumentResolver.php:65 Stack trace: #0 /home/domains/XXX/public_html/vendor/ckfinder/ckfinder-laravel-package/_connector/ArgumentResolver.php(65): CKSource\CKFinder\ExceptionHandler->errorHandler(8192, 'Method Reflecti...', '/home/...', 65) #1 /home/domains/XXX/public_html/vendor/symfony/http-kernel/HttpKernel.php(149): CKSource\CKFinder\ArgumentResolver->getArguments(Object(Illuminate\Http\Request), Array) #2 /home/domains/XXX/public_html/vendor/symfony/http-kernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Illuminate\Http\Request), 1) #3 /home/domains/XXX/public_html/vendor/ckfinder/ckfinder-laravel-package/_connector/CKFinder.php(515): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Illuminate\Http\Request), 1, false) #4 /home/domains/XXX/public_html/vendor/ckfinder/ckfinder-laravel-package/src/Controller/CKFinderController.php(48): CKSource\CKFinder\CKFinder->handle(Object(Illuminate\Http\Request), 1, false) #5 /home/domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): CKSource\CKFinderBridge\Controller\CKFinderController->requestAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Http\Request)) #6 /home/domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('requestAction', Array) #7 /home/domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(CKSource\CKFinderBridge\Controller\CKFinderController), 'requestAction') #8 /home/domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\Routing\Route->runController() #9 /home/domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Routing\Route->run() #10 /home/domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #11 /home//domains/XXX/public_html/app/Http/Middleware/CustomCKFinderAuth.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #12 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CustomCKFinderAuth->handle(Object(Illuminate\Http\Request), Object(Closure)) #13 /home//domains/XXX/public_html/app/Http/Middleware/CustomCKFinderAuth.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #14 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CustomCKFinderAuth->handle(Object(Illuminate\Http\Request), Object(Closure)) #15 /home//domains/XXX/public_html/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #16 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): RenatoMarinho\LaravelPageSpeed\Middleware\PageSpeed->handle(Object(Illuminate\Http\Request), Object(Closure)) #17 /home//domains/XXX/public_html/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #18 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): RenatoMarinho\LaravelPageSpeed\Middleware\PageSpeed->handle(Object(Illuminate\Http\Request), Object(Closure)) #19 /home//domains/XXX/public_html/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #20 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): RenatoMarinho\LaravelPageSpeed\Middleware\PageSpeed->handle(Object(Illuminate\Http\Request), Object(Closure)) #21 /home//domains/XXX/public_html/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #22 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): RenatoMarinho\LaravelPageSpeed\Middleware\PageSpeed->handle(Object(Illuminate\Http\Request), Object(Closure)) #23 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #24 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure)) #25 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #26 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure)) #27 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #28 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #29 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #30 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure)) #31 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #32 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #33 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #34 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #35 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #36 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #37 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #38 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #39 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route)) #40 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #41 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #42 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request)) #43 /home//domains/XXX/public_html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #44 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure)) #45 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #46 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #47 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #48 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #49 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #50 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure)) #51 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #52 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure)) #53 /home//domains/XXX/public_html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #54 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure)) #55 /home//domains/XXX/public_html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #56 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure)) #57 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #58 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #59 /home//domains/XXX/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #60 /home//domains/XXX/public_html/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #61 {main} [] []

**Comment by koptelovav** [comment]
I have the same issue

**Comment by ereznet** [comment]
ErezNet

	
		#outlook a						{ padding:0; }
		body							{ direction: rtl; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0; background: #fff; font-family: Arial; }

		.ExternalClass					{ width: 100%; }
		.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
		img								{ outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
		a img							{ border: none; }
		.image_fix						{ display: block; }
		p								{ margin: 1em 0; }
		h1, h2, h3, h4, h5, h6			{ color: black !important; }
		h1 a, h2 a, h3 a, h4 a, h5 a, h6 a { color: blue !important; }
		h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active { color: red !important; }
		h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited { color: purple !important; }
		table							{ border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; margin: 0; padding: 0; line-height: 100% !important; text-align: center; }
		table td						{ border-collapse: collapse; }
	



	
		
			 
		
	

	
		
			
				
					 
				
				
					
						לקוח יקר,
						החל מתאריך 23.11.17, במייל זה ***@***.***) לא תינתן/תסופק תמיכה טכנית.
						אנו שמחים להציג בפניכם את מערכת ה-HelpDesk החדשה שלנו בכתובת:https://www.helpdesk.ereznet.co.il
						
							כל לקוחות ארזנט מתבקשים לבצע הרשמה למערכת בכתובת: https://www.helpdesk.ereznet.co.il/registerההרשמה בחינם, אך חשוב לזכור שעלייכם לבצע הרשמה בעזרת הכתובת דואר שעמה ביצעתם את הזמנתכם!
						
						במערכת HelpDesk ניתן למצוא מגוון רחב של פעולות:
						
							להקים/לפתוח קריאה לשירות במגוון קטגוריות.
							הקמת כרטיס מתבצעת מתוך אתרנו, כך שבמידה ותיבת הדואר שלכם לא פעילה עדיין תוכלו לשלוח פניות.
							צפייה בהסטוריית הכרטיסים שלי.
							מעקב לכרטיס, ושינוי סטטוס.
							אפשרות להוספת מידע פנימי לכרטיס: כגון סיסמאות רגישות וכתובת IP והכל בסביבה מאובטחת (SSL).
							אפשרות לעדכון כרטיס ישירות מתוך תיבת הדואר שלכם, בעזרת שליחת מייל חוזר.
							בנוסף למערכת הכרטיסים, תמצאו מאגר מידע אשר נעדכן עבור הודעות חשובות בחברתנו.
							ועוד מגוון אפשרויות אשר יפיקו תמיכה ושליטה טובה יותר לקהל לקוחותינו.
						
						נשמח לעמוד לשירותכם :)
					
				
				
					 
				
				
					
						בברכה,צוות ארזנט - פתרונות אינטרנטמחלקת תמיכה טכניתטלפון משרד: 077-2148004 | פקס: 077-2148005כתובת אתרינו: https://www.ErezNet.co.il

**Comment by koptelovav** [comment]
I found the problem in ArgumentResolver:65. Need to replace `$reflectionClass = $param->getClass()` with ` $reflectionClass = $param->getType() && !$param->getType()->isBuiltin() ? new ReflectionClass($param->getType()->getName()) : null;`

**Comment by d4rkr3pt0r** [comment]
> 
> 
> I found the problem in ArgumentResolver:65. Need to replace `$reflectionClass = new \ReflectionClass($param->getType()->getName()`

Same issue here but changing files inside `vendor` folder is not a good idea. Hope they update the package soon.

**Comment by ereznet** [comment]
v\:* {behavior:url(#default#VML);display:inline-block;}
		o\:* {behavior:url(#default#VML);display:inline-block;}
		w\:* {behavior:url(#default#VML);display:inline-block;}
		html {min-height: 100%;}
		body {direction:rtl;width:100% !important;min-width:100%;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;margin: 0;Margin: 0;padding: 0;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;background-color: #efefef;text-align: right;font-family: Arial, sans-serif;font-size: 15px;line-height: 21px;}
		a {color:#40ba56 !important;}
		table {border-spacing: 0;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;}
		img {outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;height: auto;}
		/* ensure that clients don't add any padding or spaces around the email design and allow us to style emails for the entire width of the preview pane */
		body,#bodyTable {height:100% !important;width:100% !important;margin:0;padding:0;}
		/* Ensures Webkit- and Windows-based clients don't automatically resize the email text. */
		body,table,td,p,a,li,blockquote {-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;}
		/* Forces Yahoo! to display emails at full width */
		.thread-item.expanded .thread-body .body, .msg-body {width: 100% !important;display: block !important;}
		/* Forces Hotmail to display emails at full width */
		.ReadMsgBody,.ExternalClass {width: 100%;background-color: #f4f4f4;}
		/* Forces Hotmail to display normal line spacing. */
		.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div {line-height:100%;}
		/* Resolves webkit padding issue. */
		table {border-spacing:0;}
		/* Resolves the Outlook 2007, 2010, and Gmail td padding issue, and removes spacing around tables that Outlook adds. */
		table,td {border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;}
		/* Corrects the way Internet Explorer renders resized images in emails. */
		img {-ms-interpolation-mode: bicubic;}
		/* Ensures images don't have borders or text-decorations applied to them by default. */
		img,a img {border:0;outline:none;text-decoration:none;}
		/* Styles Yahoo's auto-sensing link color and border */
		.yshortcuts a {border-bottom: none !important;}
		/* Styles the tel URL scheme */
		a[href^=tel],.mobile_link,.mobile_link a {color:#222222 !important;text-decoration: underline !Important;}
		/* Media queries for when the viewport is smaller than the default email width but not too narrow. */
		@media screen and (max-device-width: 600px), screen and (max-width: 600px) {
			/* Constrains email width for small screens */
			table[class="email-container"] {width: 100% !important;}
			/* Constrains tables for small screens */
			table[class="fluid"] {width: 100% !important;}
			/* Forces images to resize to full width of their container */
			img[class="fluid"],img[class="force-col-center"] {width: 100% !important;max-width: 100% !important;height: auto !important;}
			/* And centers these ones */
			img[class="force-col-center"] {margin: auto !important;}
			/* Forces table cells into rows */
			td[class="force-col"],td[class="force-col-center"] {display: block !important;width: 100% !important;clear: both;}
			/* And centers these ones */
			td[class="force-col-center"] {text-align: center !important;}
			/* Forces table cells into rows */
			/* Floats a previously stacked image to the left */
			img[class="col-3-img-l"] {float: left;margin: 0 15px 15px 0;}
			/* Floats a previously stacked image to the right */
			img[class="col-3-img-r"] {float: right;margin: 0 0 15px 15px;}
			/* Makes buttons full width */
			table[class="button"] {width: 100% !important;}
		}
		/* Media queries for when the viewport is narrow. */
		/* Rules prefixed with 'hh-' (for 'handheld') repeat much of what's above, but these don't trigger until the smaller screen width. */
		@media screen and (max-device-width: 425px), screen and (max-width: 425px) {
			/* Helper only visible on handhelds. All styles are inline along with a `display:none`, which this class overrides */
			div[class="hh-visible"] {display: block !important;}
			/* Center stuff */
			div[class="hh-center"] {text-align: center;width: 100% !important;}
			/* Constrain tables for small screens */
			table[class="hh-fluid"] {width: 100% !important;}
			/* Force images to resize to full width of their container */
			img[class="hh-fluid"],img[class="hh-force-col-center"] {width: 100% !important;max-width: 100% !important;height: auto !important;}
			/* And center these ones */
			img[class="hh-force-col-center"] {margin: auto !important;}
			/* Force table cells into rows */
			td[class="hh-force-col"],td[class="hh-force-col-center"] {display: block !important;width: 100% !important;clear: both;}
			/* And center these ones */
			td[class="hh-force-col-center"] {text-align: center !important;}
			/* Stack the previously floated images */
			img[class="col-3-img-l"],img[class="col-3-img-r"] {float: none !important;margin: 15px auto !important;text-align: center !important;}
		}
	



	
			
				
					
						
					
				
			
			
			
				
					
					
						
						
							
								
								
								
							
						
						
					
					
					
						
							
							
								
								
									
										לקוח יקר,
									
								
								
							
							
							
								
								
									תיבת מייל זו ***@***.***) משמשת כתיבת מערכת ואינה נבדקת לעולם!
									לפניות בנושא מכירות והזמנת שירותים נא לפנות ל ***@***.***
									פניות לתמיכה טכנית נא לפתוח כרטיס שירות בHELPDESK שלנו בלבד
									
										
											
											 מעבר ל HELPDESK 
											
											
										
									
									
									
									בברכה,צוות Ereznet - Internet solutionsנשמח לעמוד לשירותכם :)
								
								
							
							
						
					

					
					
						
							
						
					
					
						
							
								
									
										
										
											
												
													
													
													כרטיס לתמיכה
												
												
												יש לך שאלה / בעיה ? סתם רוצה לשוחח ?אין דבר שצוות התמיכה המקצועי שלנו לא יוכל לעזור
											
										
										
									
								
							
							
							
								
									
										
										
											
												
													
													
													שרת וירטואלי VPS
												
												
												מעוניין לחסוך בעלויות ולקבל ביצועים ללא פשרות ?עבור עכשיו לשרתי הVPS המהירים שלנו
											
										
										
									
								
							
						
					
					
						
							
							
								
									הודעה זאת נשלחה אלייך בדיוור ישיר בעקבות פנייתך למייל שלנולתשומת ליבך, לא ניתן להשיב לדבר דואר זה, כיוון שכתובת הדואר ממנה נשלחה ההודעה אינה נבדקת
								
							
							
								
							
							
								
									תנאי שימוש
									   |   
									הצהרת פרטיות
									   |   
									לאתר EREZNET
									
									
									COPYRIGHT © EREZNET LTD

**Comment by sebastiansulinski** [comment]
Got reply from CKSource saying they will try to fix it within a couple of days 🤞

**Comment by zaak** [comment]
@ereznet: Thank you for detailed report, it was very helpful. The issue has been fixed in the latest version.

**Comment by sebastiansulinski** [comment]
@zaak which version is it exactly please? I've tried `^3.5.2.1` but getting error saying

```
Root composer.json requires ckfinder/ckfinder-laravel-package ^3.5.2.1, found ckfinder/ckfinder-laravel-package[dev-master, v3.4.4, ..., v3.5.2] but it does not match the constraint.
```

When freshly installing the package and then loading it within Laravel I'm back to error `110` `Unknown error`.

**Comment by zaak** [comment]
@sebastiansulinski: Oops, sorry. Looks like Packagist's auto-update did not fetch the new version for some reason. Please try now.

**Comment by sebastiansulinski** [comment]
Thanks @zaak
